// Generated by https://quicktype.io

import Foundation

struct Usd {
  let success: Bool
  let message: String
  let result: [Result]
}

struct Result {
  let marketName: String
  let high, low, volume, last: Double
  let baseVolume: Double
  let timeStamp: String
  let bid, ask: Double
  let openBuyOrders, openSellOrders: Int
  let prevDay: Double
  let created: String
}
